import os
import sys
import pandas as pd

# Alpaca Trading API Imports
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce

# Alpaca Market Data API Imports
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockLatestTradeRequest


# ----------------------------------------------------------------------
# 1. Configuration & Initialization
# ----------------------------------------------------------------------
API_KEY = os.getenv("ALPACA_API_KEY", "PKTZD2HHJ2Q5P4BKJRPH3C4K4S")
SECRET_KEY = os.getenv("ALPACA_SECRET_KEY", "5pLkR4rKksvcdiLLZ7QqWrj9J4YSzbBFVULM9y7iJzy3")
PAPER_TRADING = True  # Set to False for Live Trading

# Initialize API clients
trading_client = TradingClient(API_KEY, SECRET_KEY, paper=PAPER_TRADING)
data_client = StockHistoricalDataClient(API_KEY, SECRET_KEY)


# ----------------------------------------------------------------------
# 2. Price Resolver Helper
# ----------------------------------------------------------------------
def resolve_price(ticker, fallback_close):
    """
    Attempts to fetch the real-time execution price using StockHistoricalDataClient.
    If the API fails or is restricted, falls back to the CSV closing price.
    """
    try:
        request_params = StockLatestTradeRequest(symbol_or_symbols=ticker)
        latest_trade = data_client.get_stock_latest_trade(request_params)
        return float(latest_trade[ticker].price)
    except Exception as e:
        print(f"  [!] Live data lookup failed for {ticker} ({e}). Falling back to CSV close: ${fallback_close:.2f}")
        return fallback_close


# ----------------------------------------------------------------------
# 3. Core Execution Engine
# ----------------------------------------------------------------------
def execute_quant_trades(target_file="weekly_target_trade.csv", base_multiplier=1.0):
    if not os.path.exists(target_file):
        print(f"Error: Target signal file '{target_file}' not found.")
        return

    # Load target CSV generated by weekly_quant_system.py
    df = pd.read_csv(target_file)
    print(f"Loaded {len(df)} target signal records from '{target_file}'.\n")

    # Fetch current account details & open portfolio positions
    try:
        account = trading_client.get_account()
        raw_positions = trading_client.get_all_positions()
        positions = {p.symbol: int(float(p.qty)) for p in raw_positions}
        buying_power = float(account.buying_power)
    except Exception as e:
        print(f"[-] Failed to fetch Alpaca account or positions: {e}")
        return

    print("=== Alpaca Portfolio State ===")
    print(f"Portfolio Value: ${float(account.portfolio_value):,.2f}")
    print(f"Buying Power:    ${buying_power:,.2f}")
    print(f"Active Holdings: {positions if positions else 'None'}\n")
    print("==========================================")

    BASE_ALLOCATION = 1000.0 * base_multiplier

    # Iterate through signals
    for idx, row in df.iterrows():
        ticker = str(row['ticker']).strip()
        signal = str(row['signal']).strip()
        z_score = float(row.get('z_score_strength', 0.0))
        csv_close = float(row['close']) if pd.notna(row.get('close')) else None

        print(f"\n[*] Processing Signal ({idx + 1}/{len(df)}) -- Ticker: {ticker} | Action: {signal} | Z-Strength: {z_score}")

        if not csv_close or csv_close <= 0:
            print(f"  [-] Skipping {ticker}: Invalid or missing price in CSV.")
            continue

        # Get execution price (live or fallback)
        price = resolve_price(ticker, csv_close)

        # --------------------------------------------------------------
        # ACTION 1: NEW_SELL / LIQUIDATION
        # --------------------------------------------------------------
        if signal == 'NEW_SELL':
            if ticker in positions and positions[ticker] > 0:
                qty_to_sell = positions[ticker]
                print(f"  [>] NEW_SELL Signal: Liquidating full position of {qty_to_sell} shares of {ticker}...")
                try:
                    order = MarketOrderRequest(
                        symbol=ticker,
                        qty=qty_to_sell,
                        side=OrderSide.SELL,
                        time_in_force=TimeInForce.GTC
                    )
                    submitted_order = trading_client.submit_order(order)
                    print(f"  [+] SELL Order Executed: Order ID {submitted_order.id}")
                except Exception as e:
                    print(f"  [-] Failed to submit SELL order for {ticker}: {e}")
            else:
                print(f"  [-] NEW_SELL Signal for {ticker}, but no active position held in account.")

        # --------------------------------------------------------------
        # ACTION 2: NEW_BUY / ENTRY
        # --------------------------------------------------------------
        elif signal == 'NEW_BUY':
            # Dynamic scaling using Z-score (minimum multiplier baseline of 0.5)
            scaling_factor = max(z_score, 0.5)
            target_dollars = BASE_ALLOCATION * scaling_factor
            shares_to_buy = int(target_dollars // price)

            if shares_to_buy > 0:
                cost = shares_to_buy * price
                if cost <= buying_power:
                    print(f"  [>] NEW_BUY Signal: Purchasing {shares_to_buy} shares of {ticker} at ~${price:.2f} (Allocated: ${cost:,.2f})...")
                    try:
                        order = MarketOrderRequest(
                            symbol=ticker,
                            qty=shares_to_buy,
                            side=OrderSide.BUY,
                            time_in_force=TimeInForce.GTC
                        )
                        submitted_order = trading_client.submit_order(order)
                        buying_power -= cost
                        print(f"  [+] BUY Order Executed: Order ID {submitted_order.id}")
                    except Exception as e:
                        print(f"  [-] Failed to submit BUY order for {ticker}: {e}")
                else:
                    print(f"  [-] Insufficient buying power to purchase {shares_to_buy} shares of {ticker} (${cost:,.2f} required, ${buying_power:,.2f} available).")
            else:
                print(f"  [-] Target dollar allocation (${target_dollars:.2f}) too small to buy 1 share of {ticker} at ${price:.2f}.")

        # --------------------------------------------------------------
        # ACTION 3: HOLD / PASS
        # --------------------------------------------------------------
        elif signal in ['HOLD_LONG', 'HOLD_CASH']:
            print(f"  [-] {signal} state for {ticker}. Maintaining posture.")


# ----------------------------------------------------------------------
# 4. Main Entry Point
# ----------------------------------------------------------------------
if __name__ == "__main__":
    # Accept portfolio multiplier command line argument (default: 1.0)
    multiplier = float(sys.argv[1]) if len(sys.argv) > 1 else 1.0
    print(f"Starting Quant Execution Engine (Base Multiplier: {multiplier}x)...")
    execute_quant_trades("weekly_target_trade.csv", base_multiplier=multiplier)
